### ISSUE TITLE
Add box shadows

### ISSUE THREAD

**Issue by WillPower3309** [wlrfx/scenefx#13]
We should add the box shadows from upstream SwayFX to scenefx

**Comment by WillPower3309** [comment]
We should have a discussion about how we want this feature to fit into the scene API design and how it should interact with borders. In my mind we have two options:
1. Have a wlr_box parameter that users will use to specify the area they'd like the shadow to be drawn around (that way they can account for borders)
2. Have the wlr_box be determined based on the scene buffer, and tied to borders (which would also have to be tied to the scene buffer). This is my preferred option, as while it does force the user to create borders through us, this will pretty much be required to support rounded borders anyway (also, less configuration/ less to worry about for the user)

**Comment by ErikReider** [comment]
> I agree with your second option. So we'll have to add border support first before shadows

In the #16 PR we grab a stencil the size of the surface geometry, we could reuse that stencil for drawing the single, large border.

IMO, we should provide a border horizontal_size, vertical_size, a x and y offset, and of course some field for providing color(s)

**Comment by WillPower3309** [comment]
> I agree with your second option. So we'll have to add border support first before shadows

Not necessarily, as shadows need to work without borders too :) we'll just add support for making them work w borders as we merge borders

**Comment by WillPower3309** [comment]
> > I agree with your second option. So we'll have to add border support first before shadows
> 
> In the #16 PR we grab a stencil the size of the surface geometry, we could reuse that stencil for drawing the single, large border.
> 
> IMO, we should provide a border horizontal_size, vertical_size, a x and y offset, and of course some field for providing color(s). Maybe also a border radius field too but who would use a different one from the surface one though?
> 
> Edit: We should actually check how eg the Sway scene PR adds borders

I'd suspect they use the scene rect rendering function, but we may not be able to reuse the stencil as we'd need the stencil for the shadow to encompass the border region too unfortunately, unless we can resize it.

Let's keep the same radius as the surface too
