### ISSUE TITLE
Add blur

### ISSUE THREAD

**Issue by WillPower3309** [wlrfx/scenefx#14]
We should add the blur from upstream SwayFX to scenefx

**Comment by WillPower3309** [comment]
Let's wait to complete this task until https://github.com/WillPower3309/swayfx/pull/181 is done

**Comment by Shinyzenith** [comment]
Related: https://github.com/WillPower3309/swayfx/pull/219

https://github.com/WillPower3309/swayfx/pull/181 was superceeded by 219
