### ISSUE TITLE
Example tinywl : missing headers ?

### ISSUE THREAD

**Issue by lidgnulinux** [wlrfx/scenefx#26]
Hello, when I built the example tinywl, it's failed. It seems that there are missing headers. 

```
#include <types/fx/shadow_data.h>
......
#include "types/wlr_scene.h"

#include "render/fx_renderer/fx_renderer.h"
```

Is it intentional ? Thanks.

**Comment by ErikReider** [comment]
At the moment, you'll probably have to use scenefx as a subproject

**Comment by ahmadraniri** [comment]
Facing the same issue here, @ErikReider subproject of what actually ? The tinywl ?

**Comment by ErikReider** [comment]
What are you trying to build? The tinywl in the repo or a separated tinywl in a different repo?

**Comment by ErikReider** [comment]
Oh now I know what you mean, mb. Fixing....

**Comment by lidgnulinux** [comment]
Hello, Quick trial on the pull request #27 and I still face the missing headers complain.

**Comment by lidgnulinux** [comment]
Hello, Quick trial on your PR and I'm still facing the missing headers complain.

```
/home/lidg/.local/include/scenefx/fx_renderer/fx_renderer.h:15:10: fatal error: render/pass.h: No such file or directory
   15 | #include "render/pass.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:16: tinywl] Error
```

**Comment by ErikReider** [comment]
> Hello, Quick trial on your PR and I'm still facing the missing headers complain.
> 
> ```
> /home/lidg/.local/include/scenefx/fx_renderer/fx_renderer.h:15:10: fatal error: render/pass.h: No such file or directory
>    15 | #include "render/pass.h"
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:16: tinywl] Error
> ```

You should compile everything with meson, not the makefile

**Comment by ahmadraniri** [comment]
Oh my bad.

**Comment by lidgnulinux** [comment]
> You should compile everything with meson, not the makefile


I talked about the example tinywl and not the scenefx, using meson give me this : 

```
Version: 1.3.0
Source dir: /home/lidg/cmp/scenefx/tinywl
Build dir: /home/lidg/cmp/scenefx/tinywl/build
Build type: native build

ERROR: Not the project root: first statement must be a call to project()

Did you mean to run meson from the directory: "/home/lidg/cmp/scenefx"?

A full log can be found at /home/lidg/cmp/scenefx/tinywl/build/meson-logs/meson-log.txt
```

**Comment by ErikReider** [comment]
> > You should compile everything with meson, not the makefile
> 
> 
> I talked about the example tinywl and not the scenefx, using meson give me this : 
> 
> ```
> Version: 1.3.0
> Source dir: /home/lidg/cmp/scenefx/tinywl
> Build dir: /home/lidg/cmp/scenefx/tinywl/build
> Build type: native build
> 
> ERROR: Not the project root: first statement must be a call to project()
> 
> Did you mean to run meson from the directory: "/home/lidg/cmp/scenefx"?
> 
> A full log can be found at /home/lidg/cmp/scenefx/tinywl/build/meson-logs/meson-log.txt
> ```

Run the meson command in the parent directory to build scenefx. Tinywl will be built at the same time

**Comment by lidgnulinux** [comment]
> Tinywl will be built at the same time

No, it wont.

**Comment by lidgnulinux** [comment]
I built scenefx successfully but the tinywl not be built at the same time !

```
[lidg ] scenefx $ find -name "*tinywl*"
./tinywl
./tinywl/tinywl.c
```
