### ISSUE TITLE
Allow for setting per surface corner rounding

### ISSUE THREAD

**Issue by ErikReider** [wlrfx/scenefx#31]
If the comp wants to add server-side decoration, the top radii makes it look a bit weird:

![image](https://github.com/wlrfx/scenefx/assets/35975961/9e5e7c5b-bb15-4fb3-9f93-5a48c3d8022a)

**Comment by WillPower3309** [comment]
@ErikReider not sure if I followed the original description here - does #71 solve this?

**Comment by ErikReider** [comment]
> @ErikReider not sure if I followed the original description here - does #71 solve this?

Yeah, no more broken corners if the comp wants to :D
