### ISSUE TITLE
The example of tinywl becomes weird.

### ISSUE THREAD

**Issue by lidgnulinux** [wlrfx/scenefx#36]
Hello, this morning I decided to try scenefx again and I found something weird with its example (tinywl). It seems get rotated 90 degree (clockwise). I have a screenshot below. Is it intentional or the tinywl not getting update ? Thanks.

![20240413_12h09m48s_grim](https://github.com/wlrfx/scenefx/assets/99301306/b53de684-52f3-4a58-ac75-fd5962a45218)

**Comment by lidgnulinux** [comment]
I'm using wlroots 0.17.1

**Comment by ErikReider** [comment]
Might be one of my infamous "accidentally pushed some extra code" commits. I'll look into it :)

**Comment by ErikReider** [comment]
> I'm using wlroots 0.17.1
> Also, some windows are just blackscreen, like thunar, neovim-qt.

Any other applications that are affected?

**Comment by lidgnulinux** [comment]
Thanks for responding @ErikReider .

> Any other applications that are affected?

Probably alot.

**Comment by ErikReider** [comment]
![image](https://github.com/wlrfx/scenefx/assets/35975961/f72da048-9c37-4ad5-8daf-769eda767d27)
Seems to work on my end...

This patch forces the output to not be rotated. Might be something with the preferred output config being wonky on your setup?

```diff
diff --git a/tinywl/tinywl.c b/tinywl/tinywl.c
index 994574f..6bbb240 100644
--- a/tinywl/tinywl.c
+++ b/tinywl/tinywl.c
@@ -665,6 +665,8 @@ static void server_new_output(struct wl_listener *listener, void *data) {
 		wlr_output_state_set_mode(&state, mode);
 	}
 
+	wlr_output_state_set_transform(&state, WL_OUTPUT_TRANSFORM_NORMAL);
+
 	/* Atomically applies the new output state. */
 	wlr_output_commit_state(wlr_output, &state);
 	wlr_output_state_finish(&state);
```

Can you provide more screenshots of the issue?

**Comment by lidgnulinux** [comment]
It seems my Ubuntu is kinda weird. I Move on to my slackware system and it works. So probably it's my own fault. Sorry @ErikReider, to bother you hehe. Closing it now.
