### ISSUE TITLE
Branding and README

### ISSUE THREAD

**Issue by WillPower3309** [wlrfx/scenefx#43]
If we want scenefx to be adopted by other compositors, we should get some branding and create a README! benchmarks should also be included

**Comment by MrPenguin07** [comment]
Yes please.

I created a swayfx-9999 live Gentoo ebuild which was working great, now with the 0.19 it depends on scenefx and yet there are no build instructions :(

**Comment by WillPower3309** [comment]
https://github.com/wlrfx/scenefx/commit/bb349f578d696f741ffc677aa9f6db95732ea1a3

**Comment by WillPower3309** [comment]
I'd recomend any package maintainers to reference https://github.com/wlrfx/aur-packages/blob/main/scenefx/PKGBUILD :)

**Comment by WillPower3309** [comment]
> > I'd recomend any package maintainers to reference https://github.com/wlrfx/aur-packages/blob/main/scenefx/PKGBUILD :)
> 
> Cheers, my impatience got the best of me haha so despite your quick response i'd already gone ahead and created a [scenefx-9999 live git ebuild](https://github.com/MrPenguin07/ebuilds/blob/master/media-plugins/scenefx/scenefx-9999.ebuild) which lives in my repo [mrpenguin](https://github.com/MrPenguin07/ebuilds) 
> 
> It also has [swayfx-9999 ebuild](https://github.com/MrPenguin07/ebuilds/blob/master/gui-wm/swayfx/swayfx-9999.ebuild) for Gentoo users.
> 
> Appreciate your work on these projects @WillPower3309 

Wow that's awesome! Thanks for the support
