### ISSUE TITLE
How use it ?

### ISSUE THREAD

**Issue by Silitonix** [wlrfx/scenefx#52]
since I'm new to topic of Wayland compositors and i started to use labwc to my main window manager but i want change the lock using this project.
can anyone help me please !

**Comment by RicArch97** [comment]
In order for LabWC to use this, they would have to replace the use of default wlr_scene with scenefx, and then add options for the extra effects..

LabWC devs have also already mentioned that they're not interested in using this however; https://github.com/labwc/labwc/pull/1648#issuecomment-2066406703

LabWC also already has it own implementation of rounded corners and box shadows.

If you really want to use this, you could always fork LabWC and then implement scenefx

**Comment by ErikReider** [comment]
Take a look at our tinywl example in the repo. Here's my impl: https://github.com/ErikReider/fx-comp

**Comment by Silitonix** [comment]
Thank you for helping and guiding! As a tiny suggestion it is much better to have a document or what needs to be done in readme files.
