### ISSUE TITLE
Support user defined shaders

### ISSUE THREAD

**Issue by coreymwamba** [wlrfx/scenefx#53]
This is more of an feature request: when I used to use i3 I also used picom's legacy glsl shaders to turn my screen from RGB to grayscale, or invert the colours. Having looked at the source code for scenefx (after trying—and failing—to write a script that could modify gamma ramps in wlroots) I see that it uses gles fragment shaders.

So would it be possible to add that functionality to scenefx (and thus swayfx)?

**Comment by WillPower3309** [comment]
This is a good idea! I think what we want here is essentially https://github.com/WillPower3309/swayfx/issues/110

**Comment by coreymwamba** [comment]
I'm really sorry I can't help much more—I'm still learning C! But am I right in thinking that you'd need to modify the files in include/render/fx_renderer?

**Comment by WillPower3309** [comment]
closing as duplicate
