### ISSUE TITLE
Pass eyecandy data to the scene API

### ISSUE THREAD

**Issue by WillPower3309** [wlrfx/scenefx#8]
More or less a tracking issue of https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3393. We should try to solve this upsteam, and then on our end, pass the decoration data the same way that opacity is passed.

**Comment by ErikReider** [comment]
Seems like it's already been done (the opacity bit) 😅

https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4145

**Comment by WillPower3309** [comment]
Haha I had to laugh at the dialogue, good on you for messaging about it

**Comment by WillPower3309** [comment]
Could do something similar but with `wlr_scene_buffer_set_effects`? Then everything else could be identical, compositors would only need to call that function

**Comment by ErikReider** [comment]
We should also be able to pass global args to the fx_renderer. One example would be a blur toggle

**Comment by Shinyzenith** [comment]
> We should also be able to pass global args to the fx_renderer. One example would be a blur toggle

Has this landed in tinywl main branch?

**Comment by ErikReider** [comment]
> > We should also be able to pass global args to the fx_renderer. One example would be a blur toggle
> 
> Has this landed in tinywl main branch?

No. Just a reminder that we have to add this functionality :)

**Comment by WillPower3309** [comment]
> We should also be able to pass global args to the fx_renderer. One example would be a blur toggle

I'm actually not sure about this. In the SwayFX implementation, fx_renderer has no knowledge of config values, and I'm wondering if we should keep it like that for scenefx. It would simplify things a bit if we just blurred windows when specifically told, and had the compositor handle always telling us to blur if a global setting is set

**Comment by ErikReider** [comment]
> > We should also be able to pass global args to the fx_renderer. One example would be a blur toggle
> 
> I'm actually not sure about this. In the SwayFX implementation, fx_renderer has no knowledge of config values, and I'm wondering if we should keep it like that for scenefx. It would simplify things a bit if we just blurred windows when specifically told, and had the compositor handle always telling us to blur if a global setting is set

Aaah, very true! A global would be kinda redundant if it already knows that it has to blur. How are we gonna tackle this? Use the method that's used in the `deco_data_temp` branch or something else?

**Comment by WillPower3309** [comment]
Let's bring the deco_data_temp branch into a PR and we can iterate from there
